### ISSUE TITLE
Installation fails with: ModuleNotFoundError: No module named 'future'

### ISSUE THREAD

**Issue by atodorov** [gastlygem/junitparser#20]
I get a failure installing junitparser b/c the `future` package isn't installed yet:

```
..... Trying to install the new tarball inside a virtualenv
Collecting setuptools
  Using cached https://files.pythonhosted.org/packages/bf/ae/a23db1762646069742cc21393833577d3fa438eecaa59d11fb04fa57fcd5/setuptools-40.7.1-py2.py3-none-any.whl
Collecting pip
  Using cached https://files.pythonhosted.org/packages/46/dc/7fd5df840efb3e56c8b4f768793a237ec4ee59891959d6a215d63f727023/pip-19.0.1-py2.py3-none-any.whl
Installing collected packages: setuptools, pip
  Found existing installation: setuptools 28.8.0
    Uninstalling setuptools-28.8.0:
      Successfully uninstalled setuptools-28.8.0
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-19.0.1 setuptools-40.7.1
Looking in links: dist/
Collecting kiwitcms-junit.xml-plugin
Collecting junitparser==1.2.2 (from kiwitcms-junit.xml-plugin)
  Using cached https://files.pythonhosted.org/packages/77/17/1f2c12fc8aaba645c6f71b6a3b008aee2682b0179910bb258e7a6b5df547/junitparser-1.2.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-shie07zw/junitparser/setup.py", line 4, in <module>
        from junitparser import __version__
      File "/tmp/pip-install-shie07zw/junitparser/junitparser/__init__.py", line 1, in <module>
        from .junitparser import (
      File "/tmp/pip-install-shie07zw/junitparser/junitparser/junitparser.py", line 12, in <module>
        from future.utils import with_metaclass
    ModuleNotFoundError: No module named 'future'
```

You can see the script which produces this at:
https://github.com/kiwitcms/junit.xml-plugin/blob/master/tests/bin/check-build - it builds packages in my repository and tries to install them in a local virtualenv before we push to PyPI.

**Comment by gastlygem** [comment]
Please try with 1.3.1, the dependency is properly resolved with source-only package now.
